# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-30 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('JON', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.CharField(default='Runur', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(default='IC', max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='country',
            field=django_countries.fields.CountryField(default='United States', max_length=2),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(default='Runur', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='Runur', max_length=100),
        ),
    ]
