# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-31 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('JON', '0002_auto_20170730_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('value', models.CharField(default='', max_length=32)),
                ('measure', models.CharField(default='', max_length=32)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('text', models.TextField(default='')),
                ('conditions', models.ManyToManyField(to='JON.Condition')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='JON.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='drafted', max_length=64)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Subscription', max_length=64)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='program',
            name='projects',
            field=models.ManyToManyField(to='JON.Project'),
        ),
        migrations.AddField(
            model_name='program',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='JON.OrderStatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='JON.OrderType'),
        ),
        migrations.AddField(
            model_name='project',
            name='orders',
            field=models.ManyToManyField(to='JON.Order'),
        ),
    ]
