# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-31 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JON', '0003_auto_20170731_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
