# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-31 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JON', '0005_auto_20170731_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='projects',
            field=models.ManyToManyField(blank=True, to='JON.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='orders',
            field=models.ManyToManyField(blank=True, to='JON.Order'),
        ),
    ]
