# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-01 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JON', '0006_auto_20170731_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(choices=[(0, 'Drafted'), (1, 'Created'), (2, 'Ordered'), (3, 'En Route'), (4, 'Completed')], default=0, max_length=64),
        ),
    ]
