# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-01 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JON', '0008_auto_20170801_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(choices=[(1, 'Drafted'), (2, 'Created'), (3, 'Ordered'), (4, 'En Route'), (5, 'Completed')], default=1, max_length=16),
        ),
    ]
