# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-03 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JON', '0014_auto_20170803_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='tags',
        ),
    ]
