# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-08 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JON', '0017_auto_20170806_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.IntegerField(choices=[(0, 'Drafted'), (1, 'Created'), (2, 'Ordered'), (3, 'En Route'), (4, 'Completed')], default=0),
        ),
    ]
