# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-08 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JON', '0019_asset_inventory_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='JON.Employee')),
                ('vehicles', models.ManyToManyField(to='JON.Vehicle')),
            ],
            bases=('JON.employee',),
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventories'},
        ),
        migrations.AddField(
            model_name='contract',
            name='buyer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='JON.AccountUser'),
        ),
        migrations.AddField(
            model_name='contract',
            name='delivery_promise',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='JON.Account'),
        ),
        migrations.AddField(
            model_name='contract',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JON.Vehicle'),
        ),
        migrations.AddField(
            model_name='contract',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JON.Driver'),
        ),
    ]
