# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-08 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JON', '0021_remove_contract_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Drafted'), (1, 'Created'), (2, 'Ordered'), (3, 'En Route'), (4, 'Completed')], default=0),
        ),
    ]
