# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-08 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JON', '0022_auto_20170808_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
