# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-08 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JON', '0025_auto_20170808_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JON.AccountUser'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JON.Account'),
        ),
    ]
