# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-11 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JON', '0029_auto_20170809_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='cargo_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
