# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-11 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JON', '0030_vehicle_cargo_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('bicycle', 'Bicycle'), ('motorcycle', 'Motorcycle')], default='car', max_length=16),
        ),
    ]
