# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-14 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JON', '0032_auto_20170811_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicles',
            field=models.ManyToManyField(blank=True, to='JON.Vehicle'),
        ),
        migrations.AlterField(
            model_name='program',
            name='projects',
            field=models.ManyToManyField(blank=True, to='JON.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='orders',
            field=models.ManyToManyField(blank=True, to='JON.Order'),
        ),
    ]
