# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-14 13:44
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('JON', '0033_auto_20170814_1252'),
    ]

    operations = [
        CreateExtension('postgis'),
    ]
