# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-14 13:57
from __future__ import unicode_literals

from django.db import migrations
import location_field.models.plain
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('JON', '0034_PostGisExtension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='location',
        ),
        migrations.AddField(
            model_name='place',
            name='latlong',
            field=location_field.models.spatial.LocationField(default='POINT(0.0 0.0)', srid=4326),
        ),
        migrations.AddField(
            model_name='place',
            name='location_plain',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
