# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-14 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JON', '0035_auto_20170814_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='latlong',
            new_name='location',
        ),
    ]
