# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-14 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('JON', '0036_auto_20170814_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='county',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=location_field.models.spatial.LocationField(blank=True, default='POINT(0.0 0.0)', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='place',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='zipcode',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
