# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-14 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JON', '0037_auto_20170814_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JON.Place'),
        ),
    ]
