# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-14 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JON', '0038_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='county',
        ),
    ]
