# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-14 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JON', '0040_auto_20170814_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='location_plain',
        ),
    ]
