# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-15 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JON', '0041_remove_place_location_plain'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='pos',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JON.Place'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
